services:
    app:
      container_name: fast_python_api
      build: ./
      depends_on:
        - db
      command: >
        bash -c "alembic upgrade head && uvicorn fast_python_api.main:app --host 0.0.0.0 --port 8000"

      volumes:
        - ./:/app
      ports:
        - "8000:8000"
      restart: always
      env_file:
        - ./.env

    db:
      container_name: fast_python_api_db
      image: postgres
      environment:
        - POSTGRES_DB=fast_python_api
        - POSTGRES_USER=${POSTGRES_DB_USER}
        - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      ports:
        - ${POSTGRES_DB_HOST_PORT}:5432
      volumes:
        - ./db_data:/var/lib/postgresql/data
      restart: always
