services:
  app:
    container_name: fast_python_api
    image: fast_python_api:latest
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        echo '>>> Running Alembic migrations...';
        alembic upgrade head;
        echo '>>> Running init_user script...';
        python -m fast_python_api.script.init_user;
        echo '>>> Starting Uvicorn...';
        uvicorn fast_python_api.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env

  db:
    container_name: fast_python_api_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=fast_python_api
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_DB_HOST_PORT}:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d fast_python_api || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
