"""empty message

Revision ID: f3da9db8b451
Revises: 20a23c2363af
Create Date: 2025-02-12 18:00:06.009238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3da9db8b451'
down_revision: Union[str, None] = '20a23c2363af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'role')
    # ### end Alembic commands ###
